version: '3.8'

# Enable VPN
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24

services:
  sqlserver:
    image: 'mcr.microsoft.com/mssql/server:2019-latest'
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Bytutsenare!"
      MSSQL_PID: "Express"
    ports:
      - "1432:1433"