// <auto-generated />
using LivApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LivApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220702181955_AddData")]
    partial class AddData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LivApi.Models.Insurance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("GuaranteeAmount")
                        .HasColumnType("float");

                    b.Property<double>("GuaranteeTime")
                        .HasColumnType("float");

                    b.Property<int>("InsuranceId")
                        .HasColumnType("int");

                    b.Property<double>("PaymentTime")
                        .HasColumnType("float");

                    b.Property<int>("PersonalId")
                        .HasColumnType("int");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Table")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("z")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Insurances");
                });
#pragma warning restore 612, 618
        }
    }
}
